---
version: 2.1


jobs:
  lint:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout
      - run: terraform init
      - run: terraform fmt -check=true
      - run: terraform validate
      - run: rm -rf .terraform
      - run: terraform -v


workflows:
  terraform_lint:
    jobs:
      - lint