---
version: 2.1

jobs:
  lint:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout
      - run: terraform init
      - run: terraform fmt -check=true
      - run: terraform validate
      - run: rm -rf .terraform
      - run: terraform -v

  terraform_plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - run: echo "$GOOGLE_CREDENTIAL_FILE_CONTENT" > /tmp/account.json
      - run: export GOOGLE_APPLICATION_CREDENTIALS='/tmp/account.json'
      - run: terraform plan
     

workflows:
  terraform_pipeline:
    jobs:
      - lint
      - terraform_plan:
          requires:
            - lint
          context:
            - gcp_dev_context