---
version: 2.1


jobs:
  lint:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout
      - run: terraform init
      - run: terraform fmt -check=true
      - run: terraform validate
      - run: rm -rf .terraform
      - run: terraform -v
   plan:
     docker:
      - image: hashicorp/terraform:light
     steps:
       - echo "$GOOGLE_CREDENTIAL_FILE_CONTENT" > /tmp/account.json
       - export GOOGLE_APPLICATION_CREDENTIALS='/tmp/account.json'
       - terraform plan
     


workflows:
  terraform_lint:
    jobs:
      - lint
      - terraform_plan:
          requires:
            - terraform_lint
          context:
            - gcp_dev_context
     
