---
version: 2.1

jobs:
  lint:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout
      - run: terraform init
      - run: terraform fmt -check=true
      - run: terraform validate
      - run: rm -rf .terraform
      - run: terraform -v

  terraform_plan:
    docker:
      - image: sjmiller609/helm-kubectl-terraform:latest
    steps:
      - checkout
      - run: ls -l
      - run: pipeline/run.sh
     

workflows:
  terraform_pipeline:
    jobs:
      - terraform_plan:
          context:
            - gcp_dev_context
